defaults:
  - dataset: [llff]
  - frame_sampler: overfit
  - flow: raft
  - tracking: cotracker
  - model/backbone: midas
  - model/intrinsics: softmin
  - model/extrinsics: procrustes
  - loss: [flow, tracking]
  - visualizer: [summary, trajectory]
  - _self_

wandb:
  project: flowmap
  mode: disabled
  name: placeholder
  group: null
  tags: null

checkpoint:
  every_n_train_steps: 2000
  load: checkpoints/initialization_finetuned.ckpt

trainer:
  val_check_interval: 50
  max_steps: 2000

model_wrapper:
  patch_size: 32
  lr: 3e-5
  num_vis_frames: 8

cropping:
  # This can either be an exact shape like [180, 240] or an approximate number of
  # pixels. The default is as many pixels as 180*240.
  image_shape: 43200
  flow_scale_multiplier: 4
  patch_size: 32

track_precomputation:
  interval: 5
  radius: 20

  # Caching tracks is kind of a foot gun, so we only do so for development.
  cache_path: null

model:
  use_correspondence_weights: true

# In addition to being uploaded to wandb, the outputs are saved here.
local_save_root: null
ate_save_root: null
